name:                rcpl
version:             0.1.0.0
github:              "githubuser/rcpl"
license:             BSD3
author:              "Joachim Tilsted Kristensen"
maintainer:          "tilsted@di.ku.dk"
copyright:           "2022 Joachim Tilsted Kristensen"

extra-source-files:
- README.md

synopsis: A prototype implementation of the RCPL compliler.
category: Domain Specific Languages, Reversible Computing.

description: Please see the README on GitHub at <https://github.com/jtkristensen/rcpl/blob/main/README.md>

dependencies:
- base              >= 4.7  && < 5
- tasty             >= 1.4  && < 1.5
- tasty-hunit       >= 0.10 && < 0.11
- tasty-quickcheck  >= 0.10 && < 0.11
- tasty-smallcheck  >= 0.8  && < 0.9
- parsec            >= 3.1  && < 3.2

library:
  source-dirs: src

executables:
  rcpl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rcpl

tests:
  rcpl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rcpl
