name: main-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rwe/actions-hlint-setup@v1
    - uses: rwe/actions-hlint-run@v2
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: freckle/stack-action@v3
